[package]
name = "mqs-common"
version = "0.1.0"
authors = ["Jonas Scholl <jonas.scholl@lingumatiker.de>"]
edition = "2018"

[dependencies.async-trait]
version = "0.1.26"

[dependencies.chrono]
version = "0.4.10"
features = ["serde"]

[dependencies.http]
version = "0.2.1"

[dependencies.hyper]
version = "0.13"

[dependencies.log]
version = "0.4.8"

[dependencies.serde]
version = "1.0.106"

[dependencies.serde_derive]
version = "1.0.106"

[dependencies.serde_json]
version = "1.0.52"

[dependencies.tokio]
version = "0.2.20"
features = ["rt-core", "rt-threaded", "rt-util", "sync", "blocking", "tcp", "time"]

[dependencies.uuid]
version = "0.8.1"
features = ["serde", "v4"]
