[workspace]

members = [
    "mqs-bench",
    "mqs-cli",
    "mqs-client",
    "mqs-common",
    "mqs-server",
]

# Settings for optimal performance and longest build time
[profile.release]
opt-level = 3
debug = 2
lto = true
codegen-units = 1
