#!/bin/sh

set -e

host="$(hostname --ip-address || echo '127.0.0.1')"
# trim trailing spaces
host="$(echo "$host" | tr -d '[:space:]')"

if health="$(curl --fail --show-error --silent --location --max-time 3 "http://$host:7843/health")"; then
	if [ "$health" = "green" ]; then
		exit 0
	fi
	echo >&2 "unexpected health status: $health"
fi

exit 1
