FROM debian:stretch

RUN apt-get update && \
    apt-get upgrade -yy && \
    apt-get install -yy libpq5 && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /bench

WORKDIR /bench
CMD ["/usr/local/bin/bench"]

COPY ./bin/bench /usr/local/bin/bench
