#!/bin/sh
set -eo pipefail

host="$(hostname --ip-address || echo '127.0.0.1')"

if health="$(curl -fsSL "http://$host:8000/health")"; then
	if [ "$health" = "green" ]; then
		exit 0
	fi
	echo >&2 "unexpected health status: $health"
fi

exit 1
