edition = "2018"
enum_discrim_align_threshold = 40
format_code_in_doc_comments = true
format_strings = false
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 120
merge_imports = true
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
report_fixme = "Always"
report_todo = "Always"
struct_field_align_threshold = 40
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
comment_width = 120
ignore = [
    "server/src/schema.rs",
]
