[package]
name = "mqs-bench"
version = "0.1.0"
authors = ["Jonas Scholl <jonas.scholl@lingumatiker.de>"]
edition = "2018"

[dependencies.mqs-common]
path = "../mqs-common"

[dependencies.mqs-client]
path = "../mqs-client"

[dependencies.mqs-server]
path = "../mqs-server"

[dependencies.cached]
version = "0.12.0"

[dependencies.chrono]
version = "0.4.10"
features = []

[dependencies.dotenv]
version = "0.15.0"

[dependencies.hyper]
version = "0.13"

[dependencies.tokio]
version = "0.2.13"
features = ["rt-core", "rt-threaded", "rt-util", "sync", "blocking", "tcp", "time"]

[dependencies.log]
version = "0.4.8"

[dependencies.uuid]
version = "0.8.1"
features = ["serde", "v4"]
